# SPDX-FileCopyrightText: 2025 Jason Pena <jasonpena@awkless.com>
# SPDX-License-Identifier: MIT

[settings]
deployment = "bare_alias"
url = "git@github.com:awkless/dots-bash.git"
excluded = ["LICENSE*"]
dependencies = ["dash"]
